Ollama adapter
HarshaLLM/parrot pull request #4
Opened 2024-09-27 23:18 UTC by HarshaLLM

# OllamaAdapter Overview and Tests
### OllamaAdapter Class
The OllamaAdapter class serves as an adapter for performing model inference over PARROT-datasets using the Ollama language model. This class is responsible for managing the data, model, and prompt template, while also handling inference logic.

#### Key Attributes:

- __data: Stores the input dataset as a `pandas.DataFrame.`
- __model: Represents the Ollama model used for inference.
- __prompt: Holds the prompt template for model input.
- __chain: Chain built using the prompt and model for performing inference.

#### Key Methods:

- __init__: Initializes the adapter, performs validations on input parameters (data_frame, model_name, and prompt), and constructs the chain for model inference.

2024-09-30 18:24 UTC, BasRizk commented on parrot_ollama.py
> +    data_frame:pd.DataFrame = None,
Can you use something like flake8 or pylint?

2024-09-30 18:25 UTC, BasRizk commented on parrot_ollama.py
> +    data_frame:pd.DataFrame = None,
Can you use something like flake8 or pylint?

2024-09-30 19:06 UTC, rajvkhaitan approved these changes

2024-09-30 21:22 UTC, HarshaLLM commented
Resolved #5 within commit @80a03b5.

2024-09-30 21:23 UTC, HarshaLLM commented on parrot_ollama.py
> +    data_frame:pd.DataFrame = None,
Thank you. Will do.

2024-10-01 23:46 UTC, BasRizk requested changes

2024-10-01 23:46 UTC, BasRizk commented on parrot_ollama.py
> +        except Exception as e:
What is the point of the exception here?

2024-10-01 23:46 UTC, BasRizk commented on parrot_ollama.py
> +    __data: pd.DataFrame = None
Why are these class variables instead of instance variables if they always get assigned by the `__init__` method?

2024-10-01 23:46 UTC, BasRizk commented on parrot_ollama.py
> +                raise Exception("[OllamaAdapter] Prompt cannot be empty!")
Create other custom Exceptions please.

2024-10-01 23:46 UTC, BasRizk commented on datasets/Datasets.py
> +            self.__file__ = self.__cwd +"/datasets/"+ self.current_dataset + ".csv"
please make the `self.__file__` variable name clearer to avoid confusion with python builtin __file__

2024-10-01 23:46 UTC, BasRizk commented on test_cases.py
> +def test_OllamaAdapter_Millionaire_Test_Success():
make them all camelcase please

2024-10-01 23:46 UTC, BasRizk commented on parrot_ollama.py
> +        Helper method, which accepts a dictionary of inputs to the LLM as query and returns the response received from the LLM.
please add Args, Returns, and Raises parts of docs, here and everywhere applicable.

2024-10-01 23:47 UTC, HarshaLLM commented on parrot_ollama.py
> +        except Exception as e:
Custom exceptions are handled in an unusual way for pytest. Let me create custom exceptions like we discussed.

2024-10-01 23:48 UTC, BasRizk commented on parrot_ollama.py
> +    data_frame:pd.DataFrame = None,
if you can also add the file, commit .flake8 file, please.

2024-10-01 23:48 UTC, HarshaLLM commented on parrot_ollama.py
> +                raise Exception("[OllamaAdapter] Prompt cannot be empty!")
Roger that 🥇

2024-10-02 22:31 UTC, HarshaLLM commented on parrot_ollama.py
> +        Helper method, which accepts a dictionary of inputs to the LLM as query and returns the response received from the LLM.
Addressed #8 in [24d7c4a](https://github.com/HarshaLLM/parrot/pull/4/commits/24d7c4a4bb60c8c45f292d4a7bcfd806bbb3fb6b)

2024-10-02 22:34 UTC, HarshaLLM commented on test_cases.py
> +def test_OllamaAdapter_Millionaire_Test_Success():
Pytest does not support camel case as the first keyword for every method should be 'test' in lowercase, however, I've ensured that the test case markers are CamelCase. For the methods I've updated prototype #7 with snake_case as seen in [65062d1](https://github.com/HarshaLLM/parrot/pull/4/commits/65062d1bf19f205c92e0bfc948f8382584816c19)

2024-10-02 22:35 UTC, HarshaLLM commented on parrot_ollama.py
> +                raise Exception("[OllamaAdapter] Prompt cannot be empty!")
Addressed #9 in [e9395a8](https://github.com/HarshaLLM/parrot/pull/4/commits/e9395a828acd685a7c65258dae38334038567511)

Each module gets its own exceptions making exception handling more robust.

2024-10-02 22:46 UTC, BasRizk commented on parrot_ollama.py
> +class OllamaAdapterExceptions(Exception):
Please rename this as as singular Exception

2024-10-02 22:46 UTC, BasRizk commented on parrot_ollama.py
> +    def __init__(self,
are you using flake8 or pylint?

2024-10-02 22:46 UTC, BasRizk commented on parrot_ollama.py
> +    def __init__(self,
you can do that at the end as well, no need at this particular PR.

2024-10-02 22:46 UTC, BasRizk commented on parrot_ollama.py
> +                raise Exception(f"Model not found, download it using the CLI command 'ollama run <model-name>'")
What is this exception for? at least maybe do it like as follows:

```
except Exception as e:
      logger.error(...
      raise e
```
what do you think?

2024-10-02 22:46 UTC, BasRizk commented on datasets/Datasets.py
>  class Datasets():
rename file to lowercase please.. it seems change is not reflected.

2024-10-02 22:46 UTC, BasRizk commented on datasets/Datasets.py
> +        Raises:
I would say no need to mention Raises, if it raises nothing (or meaning undetermined).

2024-10-02 22:52 UTC, HarshaLLM commented on parrot_ollama.py
> +    def __init__(self,
Using pylance from Microsoft.

2024-10-02 22:53 UTC, HarshaLLM commented on parrot_ollama.py
> +                raise Exception(f"Model not found, download it using the CLI command 'ollama run <model-name>'")
Missed an exception here. It should be `OllamaException.RuntimeError()`

2024-10-02 22:54 UTC, HarshaLLM commented on datasets/Datasets.py
>  class Datasets():
I'm unsure why this issue persists, as I've renamed it. The commit does not reflect it, where the local file-pointer is lowercase.

2024-10-02 22:54 UTC, HarshaLLM commented on parrot_ollama.py
> +                raise Exception(f"Model not found, download it using the CLI command 'ollama run <model-name>'")
Will make the change thank you.

2024-10-02 22:55 UTC, HarshaLLM commented on parrot_ollama.py
> +class OllamaAdapterExceptions(Exception):
Done. [10f882a](https://github.com/HarshaLLM/parrot/pull/4/commits/10f882a77b8ce263bcf3a0f84daf7304b6c173ea)

2024-10-02 22:57 UTC, HarshaLLM commented on datasets/Datasets.py
> +        Raises:
Addressed here: [ff0d93c](https://github.com/HarshaLLM/parrot/pull/4/commits/ff0d93c5508db258e43b3be071bf0e8810449c65)

2024-10-02 23:04 UTC, HarshaLLM commented on parrot_ollama.py
> +                raise Exception(f"Model not found, download it using the CLI command 'ollama run <model-name>'")
Tried the change, your suggestion a better fit in this case employing it.

2024-10-02 23:20 UTC, HarshaLLM commented on parrot_ollama.py
> +                raise Exception(f"Model not found, download it using the CLI command 'ollama run <model-name>'")
Addressed within [286277d](https://github.com/HarshaLLM/parrot/pull/4/commits/286277d7a29afd1d4c7f1b218693c40f8cb681d5)

2024-10-02 23:25 UTC, BasRizk commented on datasets/Datasets.py
>  class Datasets():
please use "git mv <old_file_name> <new_file_name>", [ref](https://github.com/desktop/desktop/issues/17196).

2024-10-02 23:29 UTC, BasRizk approved these changes

2024-10-02 23:33 UTC, HarshaLLM commented
`Alexa play Do I Wanna Know by Artic Monkeys` 🧨 ✨

2024-10-02 23:33 UTC, merged